<?php

/**
 * @file
 * Module install logic.
 */

/**
 * Implements hook_uninstall().
 */
function phpexcel_uninstall() {
  foreach (array(
    'phpexcel_cache_mechanism',
    'phpexcel_phptemp_limit',
    'phpexcel_apc_cachetime',
    'phpexcel_memcache_host',
    'phpexcel_memcache_port',
    'phpexcel_memcache_cachetime',
  ) as $variable) {
    config_clear('phpexcel.settings', $variable);
  }
}
